name: CI Dzil

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
    schedule:
        - cron: '13 6 * * 0'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
    container:
      # https://hub.docker.com/r/perldocker/perl-tester
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Perl version
        run: perl -v
      - name: Regular tests
        run: |
          cpanm --notest Dist::Zilla
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --author --missing | cpanm --notest
          dzil test --author --release
